title:              Ashwani Yadav
email:              1801ee13@iitp.ac.in
description:        My Personal Blog
author:             Ashwani Yadav @ashwaniYDV
baseurl:            "/"
url:                "https://ashwaniYDV.github.io"

# Social Profiles
twitter_username:   ashyadavash
github_username:    ashwaniYDV
facebook_username:  ashwani.yadav9499
linkedin_username:  ashwaniydv

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
